version: '3'
services:
  justification-systems-database:
    image: mongo
    container_name: justification-systems-database

  justification-bus:
    image: jf-bus
    container_name: justification-bus
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - jsDatabaseUrl=mongodb://justification-systems-database:27017
    depends_on:
      - justification-systems-database

  justification-engine:
    image: jf-engine-ws
    container_name: justification-engine
    expose:
      - "8080"
    ports:
      - "8081:8080"
    environment:
      - jsDatabaseUrl=mongodb://justification-systems-database:27017
    depends_on:
      - justification-systems-database