version: '3'
services:
  justification-systems-database:
    image: mongo
    container_name: justification-systems-database

  justification-bus:
    image: jf-stack
    container_name: justification-stack
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - jsDatabaseUrl=mongodb://justification-systems-database:27017
    depends_on:
      - justification-systems-database